poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('poll/<int:pk>',views.DetailView.as_view(), name='detail'),
    path('poll/<int:pk>/results/',views.ResultsView.as_view(),name='results'),
    path('poll/<int:question_id>/vote/',views.vote,name='vote'),
]

polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('poll.urls'))
]

poll/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
"""
This app will have 2 models - a Question model and a 
Choices model. The Choices model will reference the Question model.
"""


class Question(models.Model):
    question_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date<=timezone.now()


class Choices(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
# import datetime
# Create your views here.
from .models import Question, Choices

"""
The views were initially written as function based views- but later updated to 
class based views.
"""


class IndexView(generic.ListView):
    template_name = "poll/index.html"
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "poll/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def index(request):
    # now = datetime.datetime.now()
    # local = now.astimezone()
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)


def detail(request, question_id):
    """
    The objects.get and raise 404 can be clubbed together as django provides a
    shortcut for the operation.
    """
    # try:
    #     q = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)
    # the above is a shortcut....
    context = {'question': question}
    return render(request, 'poll/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices_set.get(pk=request.POST['choice'])
    except (KeyError, Choices.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

poll/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Page</title>
</head>
<body>

<h1>{{question.question_text}}</h1>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
    {% for choice in question.choices_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="VOTE">
</form>

</body>
</html>

poll/templates/poll/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}">
    <title>Index Page</title>
</head>
<body>
<h1>Welcome to the Polls Homepage</h1>
{%if latest_question_list %}
<ul>
{% for q in latest_question_list %}
<li><a href="{% url 'poll:detail' q.id %}">{{q.question_text}}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No Questions in the polls...</p>
{% endif %}

</body>
</html>

poll/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choices_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>
</body>
</html>